node soundTest.js -f wavs/Kade-16.wav -s 1
node soundTest.js -f wavs/Samuel-19.wav -s 2
node soundTest.js -f wavs/Sonne-20.wav -s 3
node soundTest.js -f wavs/Samuel-21.wav -s 2
node soundTest.js -f wavs/Sonne-22.wav -s 3
node soundTest.js -f wavs/Samuel-23.wav -s 2
node soundTest.js -f wavs/Sonne-24.wav -s 3
node soundTest.js -f wavs/Samuel-25.wav -s 2
node soundTest.js -f wavs/Sonne-26.wav -s 3
node soundTest.js -f wavs/Samuel-27.wav -s 2
node soundTest.js -f wavs/Sonne-28.wav -s 3
node soundTest.js -f wavs/Samuel-29.wav -s 2
node soundTest.js -f wavs/Sonne-30.wav -s 3
node soundTest.js -f wavs/Samuel-31.wav -s 2
node soundTest.js -f wavs/Sonneo-32.wav -s 3
node soundTest.js -f wavs/Samuel-33.wav -s 2
node soundTest.js -f wavs/Sonneo-34.wav -s 3
node soundTest.js -f wavs/Samuelo-35.wav -s 2
node soundTest.js -f wavs/Kade-36.wav -s 1
node soundTest.js -f wavs/Samuelo-37.wav -s 2
node soundTest.js -f wavs/Sonneo-38.wav -s 3
node soundTest.js -f wavs/Kade-39.wav -s 1
node soundTest.js -f wavs/Sonneo-40.wav -s 3
node soundTest.js -f wavs/Samuelo-31.wav -s 2
node soundTest.js -f wavs/Sonneoo-42.wav -s 3
node soundTest.js -f wavs/Sonneo-43.wav -s 3
node soundTest.js -f wavs/Kade-44.wav -s 1
node soundTest.js -f wavs/Sonneo-45.wav -s 3
